VERSION 0.7

FROM openjdk:11-ea-jdk-slim

WORKDIR /aeron

COPY volumes/aeron-all-1.42.1.jar .

ping:
    FROM +base
    RUN       bash -c "java -cp aeron-all-1.42.1.jar \
               -XX:+UnlockDiagnosticVMOptions \
               -XX:GuaranteedSafepointInterval=300000 \
               -Dagrona.disable.bounds.checks=true \
               -Daeron.sample.embeddedMediaDriver=true \
               -Daeron.sample.ping.channel=aeron:udp?endpoint=127.0.0.1:40124 \
               -Daeron.sample.pong.channel=aeron:udp?endpoint=127.0.0.1:40123 \
               io.aeron.samples.Ping > ping.log"

pong:
    FROM earthly/dind:alpine-3.18-docker-23.0.6-r4
    RUN apk add openjdk11
    WORKDIR /aeron
    COPY volumes/aeron-all-1.42.1.jar .
    COPY volumes/docker-compose.yml .
    RUN echo "docker0=$(ip addr show docker0 | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)" > /aeron/.env
    WITH DOCKER --compose docker-compose.yml
        #RUN export pong=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' pong) && \
        RUN docker-compose exec pong java -cp /aeron/aeron-all-1.42.1.jar \
            -XX:+UnlockDiagnosticVMOptions \
            -XX:GuaranteedSafepointInterval=300000 \
            -Dagrona.disable.bounds.checks=true \
            -Daeron.sample.embeddedMediaDriver=true \
            -Daeron.sample.ping.channel=aeron:udp?endpoint=localhost:40124 \
            -Daeron.sample.pong.channel=aeron:udp?endpoint=localhost:40123 \
            io.aeron.samples.Pong >pong.log
    END
    
all:
        BUILD +ping
        BUILD +pong